export const meta = {
  name: 'bayou-impl-main',
  description: 'Implement the remaining 16 modules with dependency-driven scheduling, then integrate until the headless smoke test and Chrome load are green',
  phases: [
    { title: 'Implement', detail: '16 modules, each starts when its dependencies finish' },
    { title: 'Integrate', detail: 'build → smoke → modules → fix, until green' },
    { title: 'Chrome', detail: 'real headless Chrome load, runtime errors, screenshots' },
  ],
}
const ROOT = '/Users/joshfleig/Desktop/Claude/bayou-state'
const SCRATCH = '/private/tmp/claude-502/-Users-joshfleig-Desktop-Claude/fb39c7b3-595d-4955-a705-28fe9ff8fb98/scratchpad'

const RESULT = { type: 'object', properties: {
  file: { type: 'string' }, lines: { type: 'number' },
  publicSurface: { type: 'array', items: { type: 'string' } },
  tier1Complete: { type: 'boolean' }, tier2Done: { type: 'array', items: { type: 'string' } }, tier2Skipped: { type: 'array', items: { type: 'string' } },
  deviations: { type: 'array', items: { type: 'string' } }, testOutput: { type: 'string' }, knownGaps: { type: 'array', items: { type: 'string' } },
}, required: ['file', 'lines', 'publicSurface', 'tier1Complete', 'tier2Done', 'tier2Skipped', 'deviations', 'testOutput', 'knownGaps'] }

// Dependency graph. data/terrain/sprites were built in wave 0 and are assumed present.
const MODULES = {
  hydro:             { deps: [], extra: `hydro.js is the make-or-break system (GDD §6.1 in full, §6.2 surge, §6.9 if present): the feet-based head-difference cellular automaton at 4 Hz over the active set, rain intake/runoff/saturation, canals (×8 conductance, culverts, floodgates), levees as raised crests with integrity/overtopping/breach, pumps in tile-ft/day, retention ponds, marsh/preserve surge head loss, the surge front entering through water tiles (never a BFS fill), drained-marsh conversion, flooded-building detection, Flood Risk prediction, and the protection flood-fill / gap detector if ARCHITECTURE.md assigns it here. selfTest must run the GDD §6.1.11 acceptance tests (T1–T8 or however many exist) on a generated map and assert their expected outcomes. Performance: the full-map worst case must stay within the §15.3 budget; use typed arrays and an active-set list.` },
  weather:           { deps: [], extra: `weather.js owns the calendar and sky clock (GDD §9 in full), seasons, heat index, the rain scheduler and drifting thunderstorm cells, the hurricane lifecycle (cone, watch, bands, landfall set piece timeline in ticks, eye, passed, recovery — GDD §6.2), festival dates, and the set-piece calendar freeze rules in ARCHITECTURE.md. selfTest: a year of calendar events fires in order; hurricane season bounds; a forced storm reaches every phase in the right tick counts.` },
  wildlife:          { deps: [], extra: `wildlife.js owns gators (dens, wanders, attractors, comic incidents, Le Grand), nutria burrowing, the mosquito field, egrets/spoonbills/fireflies spawners, the Wildlife Officer behavior, and the ecology score (GDD §6.3–§6.8). selfTest: mosquito density rules from standing water; gator wander targets respect preserves and fences; ecology composition.` },
  buildings:         { deps: [], extra: `buildings.js owns placement validation for every catalog row (footprints, terrain rules, path adjacency, unlock rules, pilings auto-application, road-within-N, water-adjacent rules), costs with terrain modifiers, construction timelines, effects and coverage maps (power/water/dining/happiness radii), repair/demolish/undo, levee integrity writers, the protection flood-fill and gap detector if assigned here, auto-naming, policy toggles, and the drag tools writing the surface layer (GDD §4 and §0.3 in full). selfTest: every row can be placed somewhere on a generated map via a spiral search; illegal placements are rejected with the documented reasons; cost math matches §0.3 examples.` },
  economy:           { deps: [], extra: `economy.js owns cash, tuition, state funding, donations, research, athletics ledger, rolling enrollment/admissions, prestige composite with monthly lerp, happiness with the timed-modifier table, Board cards, failure-state cards, Endowment, monthly statement, Runway (GDD §5 in full). selfTest: run the §5.7 five-year projection with the scripted build order and assert the money curve stays within the documented bands; no negative students; prestige bounded.` },
  agents:            { deps: [], extra: `agents.js owns student agents (count formula, phase-bucket schedules, A* with route cache and per-tick budget, walk classes by surface/depth, reactions: flee gators, shelter in storms, splash, tailgate), radius-effect sampling for happiness, desire lines (wear array), and the visible officer/fogger/pirogue vehicles if assigned here (GDD §7). selfTest: agents reach class on a generated map with paths; no agent leaves bounds; A* budget respected.` },
  sports:            { deps: [], extra: `sports.js owns the football season schedule, named coach and starters, recruiting, team rating, win probability, the quarter-by-quarter score model, halftime decision, attendance, game-day set piece timeline in ticks, auto-sim montage, tailgates, rivalries, Play Through It (GDD §8). selfTest: a full season resolves with a valid record; win prob bounded; score model produces plausible finals.` },
  sprites_buildings: { deps: [], extra: `sprites_buildings.js is the parameterized building painter driven by catalog paint descriptors (GDD §12.3, §4 visual lines, ARCHITECTURE.md §6): every one of the 43 rows must render distinctly at 1× and 2× with construction, damaged, flooded, night-lit and pilings variants, plus the stadium tiers and the Founders' Hall Louisiana look (cream stucco, red-tile hip roof, columns). Extend BSU.sprites exactly as sprites.js documents. Verify visually: write ${SCRATCH}/buildings-preview.html inlining contract.js + data.js + sprites.js + your file, draw a contact sheet of all rows and variants, screenshot with test/browser.mjs, READ the PNG and iterate until every building reads clearly and looks handsome.` },
  sprites_entities:  { deps: [], extra: `sprites_entities.js paints agents (students with 2–4 frame walk cycles, purple/gold clothing variants, umbrellas in rain), gators (walk/swim/lunge, Le Grand), nutria, egrets/spoonbills, the fogger truck, officer, pirogues, floats, vehicles, particles atlases (rain, fireflies, petals, smoke, sparks, fireworks), and weather/lighting sprites (GDD §12, ARCHITECTURE.md §6). Extend BSU.sprites as sprites.js documents. Verify visually with a contact sheet at ${SCRATCH}/entities-preview.html via test/browser.mjs; READ the PNG and iterate.` },
  audio:             { deps: [], extra: `audio.js is WebAudio synthesis only (GDD §13): ambience layers (frogs, cicadas, rain, thunder, wind, crowd), UI stings, the brass score sting, a short procedural zydeco/brass motif; created lazily on first user gesture; muted by default; every function is a safe no-op when AudioContext is missing (headless). selfTest must pass without AudioContext.` },
  render:            { deps: ['sprites_buildings', 'sprites_entities'], extra: `render.js is the core renderer (GDD §12, ARCHITECTURE.md §6): camera with bounds and zoom steps, the 8×8 chunk cache of baked terrain with dirty flags, water pass, surfaces, the depth-sorted entity list with the documented sort key, construction/damage/flood states, overlays (flood risk, mosquito, coverage, prestige), minimap, postcard export, and the render.frame(t) entry used by session.js and BSU.headless.render(). Must draw correctly on the domstub (no-op) without throwing and be fast in Chrome: verify with test/browser.mjs using a scratch HTML that inlines all existing modules and boots a generated map (if session.js does not exist yet, write a minimal boot in the scratch HTML), screenshot at 1×, 0.5× and 2×, READ the PNGs and iterate until the campus and swamp look genuinely beautiful.` },
  render_fx:         { deps: ['render'], extra: `render_fx.js extends BSU.render with the atmosphere (GDD §12): day/night tint from the sky clock, the lights pass with cached radial sprites, fog/mist over water, rain lines and puddle rings, lightning flashes, wind-blown moss and rain, fireflies at night, heat shimmer (Tier 2), fireworks, particle pool with the documented caps, screen shake, and the performance guardrail chip. Verify with test/browser.mjs screenshots at dawn/day/dusk/night and in rain; READ the PNGs and iterate.` },
  ui:                { deps: ['buildings', 'economy', 'weather', 'hydro', 'sports', 'wildlife'], extra: `ui.js owns the DOM and src/style.css (GDD §11, ARCHITECTURE.md §7): build the HUD, palette with tabs/unlock pips, inspect panel, ticker, toasts and decision cards, title screen, settings, the input state machine (mouse, wheel, trackpad two-finger pan and pinch, keyboard map with precedence, touch as Tier 2), ghost preview through buildings.canPlace, drag tools, overlays toggle, speed controls, tooltips, and the debug panel. Write src/style.css with the purple/gold token palette, a clean modern game HUD look (rounded translucent panels, crisp system-ui type, gold accents), and layout that works at 1280×800 and 1440×900. Verify in test/browser.mjs with clicks and screenshots; READ the PNGs and iterate.` },
  ui_panels:         { deps: ['ui'], extra: `ui_panels.js extends BSU.ui with the Budget, Storm, Season, Milestones, Almanac, Board-card and settings panels and the postcard button (GDD §11, ARCHITECTURE.md §7), matching ui.js's DOM conventions and CSS. Verify with test/browser.mjs by opening every panel and screenshotting; READ the PNGs and iterate.` },
  progress:          { deps: ['buildings', 'economy', 'weather', 'sports', 'agents', 'wildlife', 'hydro'], extra: `progress.js owns the tutorial script and the first two minutes (GDD §10.1 step by step), the objective chain (§10.2), interrupt/background objectives, milestones/achievements (§10.5), event-triggered unlocks, Board of Regents cards, the Founders' Day recap, the scripted Year-1 storm and the scripted first night game, and skipTutorial semantics. It is the only module allowed to script other modules. selfTest: with skipTutorial the chain still evaluates; with the tutorial, the scripted beats fire in order under headless ticks.` },
  session:           { deps: ['ui', 'ui_panels', 'render', 'render_fx', 'progress', 'audio'], extra: `session.js is the boot orchestrator (ARCHITECTURE.md §9 and docs/HEADLESS_API.md, authoritative): init order, newGame/continue, title screen hand-off, the fixed-step main loop with the 8-tick cap and interpolation, speed handling, set-piece calendar freeze ownership, save/load/autosave with schema v1 and migration, localStorage try/catch with in-memory fallback, and the COMPLETE BSU.headless implementation (tick, render, snapshot, findSpot, place, forceHurricane, click, key, fastForwardDays, state). It must make test/smoke.mjs and test/modules.mjs pass: run \`node build.mjs --check && node test/smoke.mjs && node test/modules.mjs\` yourself and fix what is yours; for failures inside other modules, append precise notes to docs/INTEGRATION_NOTES.md (file, function, what throws) — do not edit them. You may adjust src/index.template.html only if ARCHITECTURE.md §7 requires more than #app.` },
}

const impl = (name, cfg) => {
  const file = name + '.js'
  const deps = cfg.deps.length ? `Your direct dependencies ${cfg.deps.map(d => 'src/js/' + d + '.js').join(', ')} have been implemented: read their ACTUAL source and match their real behavior (they are the truth where they differ trivially from the docs; for real contract violations, append a note to docs/INTEGRATION_NOTES.md and code defensively). If one is missing, code against ARCHITECTURE.md.` : `Foundation modules src/js/data.js, src/js/terrain.js and src/js/sprites.js exist: read the ones you use.`
  return `You are implementing ONE module of BAYOU STATE, a SimCity-style university-in-a-swamp game delivered as a single HTML file (vanilla JS + Canvas 2D, no libraries, no network, no ES modules). Working dir: ${ROOT}.
You own exactly: src/js/${file}${name === 'ui' ? ' and src/style.css' : ''}. Do not edit any other src file. You may append to docs/INTEGRATION_NOTES.md under a '## ${file}' heading and create test/unit/${name}.test.mjs.

Read IN FULL before writing code: docs/ARCHITECTURE.md (the authoritative module contract), docs/briefs/${name}.md (your checklist), src/js/contract.js (enums, params, rng, events, helpers, newState), docs/INTEGRATION_NOTES.md (notes from other implementers). Read the GDD sections your brief cites in docs/GDD.md. ${deps} ${cfg.extra}

Requirements:
- Implement EVERYTHING in your brief's Tier 1 checklist completely, then Tier 2. No TODOs, no stubs, no 'simplified for now'. Every number comes from BSU.params (note missing constants in INTEGRATION_NOTES.md and use a local const with the GDD value meanwhile).
- Module shape: 'use strict' IIFE extending window.BSU exactly as ARCHITECTURE.md specifies (init/reset/tick/selfTest lifecycle as applicable). Zero DOM/timer/audio access at definition time. Must load in Node through test/domstub.mjs.
- Determinism: all simulation randomness through BSU.rng streams; never Math.random in sim code.
- Robustness: no exception may escape your public functions on any input; guard array bounds; never produce NaN; wrap event listeners per ARCHITECTURE.md §10.
- selfTest(): pure (no canvas), asserts the brief's listed invariants, returns {ok, notes}.
- Testing: write test/unit/${name}.test.mjs that uses makeWindow() from test/domstub.mjs + node:vm to load contract.js, existing dependency modules (skip missing ones), then your file; runs selfTest() and 3–8 scenario checks from your brief's 'Done means' list. Run \`node --check src/js/${file}\` and \`node test/unit/${name}.test.mjs\` and make them pass. Paste the real output in testOutput.
- Quality bar: this is a showcase; clean, structured, commented code, but completeness beats elegance.
Return the structured result (file, lines, publicSurface, tier1Complete, tier2Done, tier2Skipped, deviations from ARCHITECTURE.md, testOutput, knownGaps).`
}

phase('Implement')
const P = {}
const order = Object.keys(MODULES)
for (const name of order) {
  const cfg = MODULES[name]
  P[name] = Promise.all(cfg.deps.map(d => P[d])).then(() => {
    log(`starting ${name}.js`)
    return agent(impl(name, cfg), { label: `impl:${name}.js`, phase: 'Implement', schema: RESULT, effort: 'high' })
  }).catch(() => null)
}
const results = {}
for (const name of order) results[name] = await P[name]
const failed = order.filter(n => !results[n])
log(`Implemented ${order.length - failed.length}/${order.length}; failed: ${failed.join(', ') || 'none'}`)

phase('Integrate')
const INT = { type: 'object', properties: { green: { type: 'boolean' }, buildOk: { type: 'boolean' }, smokeOk: { type: 'boolean' }, modulesOk: { type: 'boolean' }, fixes: { type: 'array', items: { type: 'string' } }, blockers: { type: 'array', items: { type: 'string' } }, output: { type: 'string' } }, required: ['green', 'buildOk', 'smokeOk', 'modulesOk', 'fixes', 'blockers', 'output'] }
let green = false, rounds = 0, lastInt = null
while (!green && rounds < 4) {
  rounds++
  lastInt = await agent(`You are the integrator for BAYOU STATE (working dir ${ROOT}), round ${rounds}. All modules in src/manifest.json should now exist${failed.length ? ` EXCEPT these which failed to be written and must be implemented by you from their briefs if missing: ${failed.join(', ')}` : ''}. Read docs/INTEGRATION_NOTES.md first (every implementer's assumptions and cross-module requests), then docs/ARCHITECTURE.md §1–§5 and §9–§10.
Goal: make these three commands pass, in order: \`node build.mjs --check\`, \`node test/smoke.mjs\`, \`node test/modules.mjs\`. Also run every test/unit/*.test.mjs and report which fail.
Method: run, read the failure, find the ROOT cause (usually a contract mismatch between two modules: a renamed function, a different payload, an init-order assumption, DOM access at load time, NaN from an unguarded division), fix it in the module that violates ARCHITECTURE.md (you may edit any src file), re-run. Never weaken or delete tests to pass them; never stub out a system. Keep going until all three pass or you run out of context; if you must stop early, leave the tree building and record exactly where you stopped in docs/INTEGRATION_NOTES.md under '## integrator round ${rounds}'.
Return green=true only if all three commands exit 0. Include the final command outputs in 'output' (truncate to the last 60 lines each).`,
    { label: `integrate:${rounds}`, phase: 'Integrate', schema: INT, effort: 'high' })
  green = !!(lastInt && lastInt.green)
  log(`Integration round ${rounds}: ${green ? 'GREEN' : 'not yet'} (${lastInt ? lastInt.fixes.length : 0} fixes)`)
}

phase('Chrome')
const CH = { type: 'object', properties: { loads: { type: 'boolean' }, errors: { type: 'array', items: { type: 'string' } }, fps: { type: 'number' }, screenshots: { type: 'array', items: { type: 'string' } }, fixes: { type: 'array', items: { type: 'string' } }, notes: { type: 'string' } }, required: ['loads', 'errors', 'fps', 'screenshots', 'fixes', 'notes'] }
const chrome = await agent(`You are the browser QA engineer for BAYOU STATE (working dir ${ROOT}). Rebuild with \`node build.mjs --check\`, then use the real-Chrome harness: \`node test/browser.mjs --wait 4000 --shot ${SCRATCH}/qa-title.png --fps\` and a scripted tour via import { launch } from './test/browser.mjs' in a scratch script under ${SCRATCH}: open index.html, wait, screenshot the title screen, start a new game through the UI (find the button by evaluating document.querySelector on the ids from ARCHITECTURE.md §7 or by clicking), wait 5 s, screenshot the campus at 1×, evaluate BSU.headless.snapshot(), place a path and a dorm through the headless API and screenshot again, zoom to 0.5× and 2× (wheel or keys) with screenshots, open each panel via keyboard shortcuts with screenshots, measure fps with b.fps(3000) during rain if you can force it (BSU.weather API) and at night. READ every screenshot PNG. Fix any uncaught exception, console error, blank canvas, invisible UI, or obviously broken visual (wrong colors, sprites not drawn, HUD overlapping) at its root cause in the responsible module; rebuild and re-run until the page loads with zero errors and every screenshot shows a real, attractive game. Do not stop at 'it loads'. Return loads, the remaining errors, fps, screenshot paths, fixes made, and notes on visual issues you could not fix.`,
  { label: 'chrome-qa', phase: 'Chrome', schema: CH, effort: 'high' })

return { results, failed, integration: lastInt, chrome }
