// Generates docs/API_INDEX.md by loading every existing module in the DOM stub and introspecting BSU.*
// No LLM tokens. Usage: node tools/api-index.mjs
import { readFileSync, existsSync, writeFileSync } from 'node:fs';
import vm from 'node:vm';
import { makeWindow } from '../test/domstub.mjs';
const manifest = JSON.parse(readFileSync('src/manifest.json', 'utf8')).modules;
const win = makeWindow(); const ctx = vm.createContext(win);
const loaded = [];
for (const f of manifest) { const p = 'src/js/' + f; if (!existsSync(p)) continue; try { vm.runInContext(readFileSync(p, 'utf8'), ctx, { filename: f }); loaded.push(f); } catch (e) { console.error('load failed', f, e.message); } }
const BSU = win.BSU;
const sig = (fn) => { const s = fn.toString().replace(/\s+/g, ' '); const m = s.match(/^(?:async\s+)?(?:function\s*[\w$]*\s*)?\(([^)]*)\)/) || s.match(/^([\w$]+)\s*=>/); return m ? `(${(m[1] || '').trim()})` : '(…)'; };
let out = `# BSU API index (auto-generated by tools/api-index.mjs — do not edit)\n\nLoaded: ${loaded.join(', ')}\n\nRead this instead of the module sources. Signatures are the real ones. See docs/ARCHITECTURE.md for semantics.\n`;
const skip = new Set(['params']);
for (const key of Object.keys(BSU).sort()) {
  const v = BSU[key];
  if (v && typeof v === 'object' && !ArrayBuffer.isView(v) && !skip.has(key)) {
    const fns = Object.keys(v).filter(k => typeof v[k] === 'function');
    const vals = Object.keys(v).filter(k => typeof v[k] !== 'function');
    if (!fns.length && vals.length > 40) { out += `\n## BSU.${key}  — enum/table, ${vals.length} keys (e.g. ${vals.slice(0, 8).join(', ')})\n`; continue; }
    if (!fns.length && !vals.length) continue;
    out += `\n## BSU.${key}\n`;
    if (vals.length) out += `- values: ${vals.map(k => `${k}:${Array.isArray(v[k]) ? `array[${v[k].length}]` : typeof v[k]}`).join(', ')}\n`;
    for (const k of fns) out += `- ${key}.${k}${sig(v[k])}\n`;
  } else if (typeof v === 'function') out += `\n- BSU.${key}${sig(v)}\n`;
}
// params groups
out += `\n## BSU.params groups (${Object.keys(BSU.params).length}): ${Object.keys(BSU.params).map(g => `${g}[${Object.keys(BSU.params[g]).length}]`).join(', ')}\n`;
// state tree
try {
  const st = BSU.newState(1);
  const desc = (o, depth = 0) => Object.keys(o).map(k => { const x = o[k]; if (ArrayBuffer.isView(x)) return `${k}:${x.constructor.name}[${x.length}]`; if (Array.isArray(x)) return `${k}:array[${x.length}]`; if (x && typeof x === 'object' && depth < 1) return `${k}:{${desc(x, depth + 1).join(', ')}}`; return `${k}:${x === null ? 'null' : typeof x}`; });
  out += `\n## BSU.newState(seed) tree\n${desc(st).map(l => '- ' + l).join('\n')}\n`;
} catch (e) { out += `\n(newState failed: ${e.message})\n`; }
// module header comments (first comment block, max 25 lines)
out += `\n# Module header notes\n`;
for (const f of loaded) {
  const lines = readFileSync('src/js/' + f, 'utf8').split('\n');
  const hdr = []; for (const l of lines.slice(0, 60)) { if (/^\s*(\/\/|\/\*|\*|'use strict')/.test(l) || l.trim() === '') { if (l.trim()) hdr.push(l.replace(/^\s*(\/\/|\/\*+|\*+\/?)\s?/, '')); if (hdr.length >= 25) break; } else if (hdr.length) break; }
  out += `\n## ${f}\n${hdr.filter(Boolean).join('\n')}\n`;
}
writeFileSync('docs/API_INDEX.md', out);
console.log(`docs/API_INDEX.md written: ${out.length} chars, ~${Math.round(out.split(/\s+/).length)} words`);
